import type {
  CookProfile,
  DeliveryZone,
  Order,
  Payment,
  Rating,
  Subscription,
  User,
} from './types';

export const CURRENT_USER_ID = 'cust-1';
export const CURRENT_COOK_ID = 'cook-1';
export const CAPACITY_CAP = 20;
export const PLATFORM_FEE_PER_MEAL = 15;

export const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export const FULL_DAYS = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

export const mockUsers: User[] = [
  {
    id: 'cust-1',
    name: 'Arjun Mehta',
    role: 'customer',
    email: 'arjun@example.com',
    phone: '9876543210',
    pincode: '560001',
    locality: 'Brigade Road',
    address: '12, Brigade Road, Bengaluru',
  },
  {
    id: 'cook-1',
    name: 'Lakshmi Aunty',
    role: 'cook',
    email: 'lakshmi@example.com',
    phone: '9876501234',
    pincode: '560001',
    locality: 'Brigade Road',
  },
  {
    id: 'admin-1',
    name: 'Admin',
    role: 'admin',
    email: 'admin@dabbadiaries.app',
    phone: '0000000000',
    pincode: '',
    locality: '',
  },
];

const kitchenPhotos = [
  'https://images.pexels.com/photos/37330104/pexels-photo-37330104.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  'https://images.pexels.com/photos/11011089/pexels-photo-11011089.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  'https://images.pexels.com/photos/8380203/pexels-photo-8380203.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  'https://images.pexels.com/photos/36082977/pexels-photo-36082977.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
];

export const mockCooks: CookProfile[] = [
  {
    id: 'cook-5',
    userId: 'cook-5',
    name: 'Neha Sharma Kitchen',
    tagline: 'North Indian ghar ka khana, fresh from Greater Noida West',
    bio: 'Fresh everyday meals with homestyle dal, seasonal sabzi, rotis, rice, and a little something sweet on weekends.',
    kitchenPhoto: kitchenPhotos[1],
    pincodes: ['201310'],
    rating: 4.8,
    ratingCount: 42,
    weeklyMenu: [
      { day: 'Mon', dish: 'Dal Tadka & Jeera Rice', description: 'Comforting yellow dal with jeera rice, roti, and salad', vegType: 'veg' },
      { day: 'Tue', dish: 'Aloo Gobi & Roti', description: 'Home-style aloo gobi with fresh rotis and pickle', vegType: 'veg' },
      { day: 'Wed', dish: 'Rajma Chawal', description: 'Slow-cooked rajma with steamed rice and salad', vegType: 'veg' },
      { day: 'Thu', dish: 'Kadhi Pakora', description: 'Tangy kadhi with pakoras, rice, and seasonal sabzi', vegType: 'veg' },
      { day: 'Fri', dish: 'Paneer Makhani & Roti', description: 'Mild paneer makhani with rotis and onion salad', vegType: 'veg' },
      { day: 'Sat', dish: 'Chole Rice', description: 'Punjabi chole with rice, pickle, and curd', vegType: 'veg' },
      { day: 'Sun', dish: 'Special Thali', description: 'Dal, two seasonal sabzis, rice, rotis, and a weekend sweet', vegType: 'veg' },
    ],
    vegType: 'veg',
    pricePerMeal: 85,
    weeklyPrice: 850,
    monthlyPrice: 3200,
    capacity: 15,
    capacityCap: CAPACITY_CAP,
    selfDelivery: true,
    selfDeliveryFee: 25,
    fssaiTier: 'basic-registration',
    fssaiNumber: 'FSSAI-GN-2026-0310',
    verificationStatus: 'approved',
    zoneId: 'zone-4',
    latitude: 28.6287,
    longitude: 77.3762,
    mealsPerDay: 1,
    activeSubscribers: 7,
  },
  {
    id: 'cook-1',
    userId: 'cook-1',
    name: 'Lakshmi Aunty',
    tagline: 'Andhra meals, the way amma makes them',
    bio: 'I have been cooking for my family and neighbours for 25 years. Every meal is made fresh in the morning — rice, dal, two curries, pickle, and a sweet on Fridays.',
    kitchenPhoto: kitchenPhotos[0],
    pincodes: ['560001', '560002'],
    rating: 4.8,
    ratingCount: 127,
    weeklyMenu: [
      { day: 'Mon', dish: 'Gongura Rice & Pappu', description: 'Sorrel leaves rice with toor dal, papad, and pickle', vegType: 'veg' },
      { day: 'Tue', dish: 'Tomato Bath & Curd', description: 'Spiced tomato rice with fresh curd and roasted papad', vegType: 'veg' },
      { day: 'Wed', dish: 'Chicken Curry & Rice', description: 'Country chicken curry with steamed rice and raita', vegType: 'non-veg' },
      { day: 'Thu', dish: 'Sambar & Lemon Rice', description: 'Mixed vegetable sambar with tangy lemon rice', vegType: 'veg' },
      { day: 'Fri', dish: 'Curd Rice & Sweet Pongal', description: 'Cooling curd rice with sweet pongal (Friday special)', vegType: 'veg' },
      { day: 'Sat', dish: 'Veg Biryani & Raitha', description: 'Dum vegetable biryani with cucumber raita', vegType: 'veg' },
      { day: 'Sun', dish: 'Mutton Biryani', description: 'Slow-cooked mutton biryani with mirchi salan', vegType: 'non-veg' },
    ],
    vegType: 'mixed',
    pricePerMeal: 70,
    weeklyPrice: 700,
    monthlyPrice: 2700,
    capacity: 15,
    capacityCap: CAPACITY_CAP,
    selfDelivery: true,
    selfDeliveryFee: 20,
    fssaiTier: 'basic-registration',
    fssaiNumber: 'FSSAI-BLR-2024-0042',
    verificationStatus: 'approved',
    zoneId: 'zone-1',
    latitude: 12.9716,
    longitude: 77.5946,
    mealsPerDay: 2,
    activeSubscribers: 12,
  },
  {
    id: 'cook-2',
    userId: 'cook-2',
    name: 'Radha Kitchen',
    tagline: 'Pure vegetarian South Indian thali',
    bio: 'A pure veg kitchen. I cook with cow ghee only, no onion-garlic on Thursdays. My thali has rice, sambar, rasam, two poriyals, and appalam.',
    kitchenPhoto: kitchenPhotos[1],
    pincodes: ['560001', '560003'],
    rating: 4.9,
    ratingCount: 89,
    weeklyMenu: [
      { day: 'Mon', dish: 'Sambar Sadam & Poriyal', description: 'Rice with mixed veg sambar, beans poriyal, and appalam', vegType: 'veg' },
      { day: 'Tue', dish: 'Rasam Rice & Potato Fry', description: 'Pepper rasam with crispy potato poriyal', vegType: 'veg' },
      { day: 'Wed', dish: 'Lemon Rice & Curd', description: 'Tangy lemon rice with fresh thick curd', vegType: 'veg' },
      { day: 'Thu', dish: 'No-Onion Garlic Thali', description: 'Special thali without onion-garlic: dal, two veg, rice, roti', vegType: 'veg' },
      { day: 'Fri', dish: 'Curd Rice & Sweet', description: 'Curd rice with curd vadai and semiya payasam', vegType: 'veg' },
      { day: 'Sat', dish: 'Veg Biryani & Raita', description: 'Kerala-style vegetable biryani with boondi raita', vegType: 'veg' },
      { day: 'Sun', dish: 'Full Meals Thali', description: 'Complete thali: rice, 2 dal, 3 veg, curd, sweet, papad', vegType: 'veg' },
    ],
    vegType: 'veg',
    pricePerMeal: 65,
    weeklyPrice: 650,
    monthlyPrice: 2500,
    capacity: 18,
    capacityCap: CAPACITY_CAP,
    selfDelivery: false,
    selfDeliveryFee: 0,
    fssaiTier: 'basic-registration',
    fssaiNumber: 'FSSAI-BLR-2024-0071',
    verificationStatus: 'approved',
    zoneId: 'zone-1',
    latitude: 12.9752,
    longitude: 77.5995,
    mealsPerDay: 2,
    activeSubscribers: 15,
  },
  {
    id: 'cook-3',
    userId: 'cook-3',
    name: 'Sunita Bhojanalaya',
    tagline: 'North Indian home-style meals',
    bio: 'From Lucknow, now cooking in Bengaluru. I make roti-sabzi-dal-chawal exactly like a proper UP home kitchen. No restaurant masala — only home-ground spices.',
    kitchenPhoto: kitchenPhotos[2],
    pincodes: ['560001', '560004'],
    rating: 4.7,
    ratingCount: 56,
    weeklyMenu: [
      { day: 'Mon', dish: 'Dal Tadka & Phulka', description: 'Yellow dal tadka with 4 phulkas and jeera rice', vegType: 'veg' },
      { day: 'Tue', dish: 'Aloo Gobi & Roti', description: 'Aloo gobi with 4 rotis and plain rice', vegType: 'veg' },
      { day: 'Wed', dish: 'Kadhai Paneer & Naan', description: 'Kadhai paneer with butter naan and salad', vegType: 'veg' },
      { day: 'Thu', dish: 'Rajma Chawal', description: 'Punjabi rajma with steamed rice and pickle', vegType: 'veg' },
      { day: 'Fri', dish: 'Chole Bhature', description: 'Spiced chole with two fluffy bhature', vegType: 'veg' },
      { day: 'Sat', dish: 'Chicken Curry & Roti', description: 'Home-style chicken curry with 4 rotis', vegType: 'non-veg' },
      { day: 'Sun', dish: 'Veg Pulao & Raita', description: 'Fragrant veg pulao with boondi raita and papad', vegType: 'veg' },
    ],
    vegType: 'mixed',
    pricePerMeal: 75,
    weeklyPrice: 750,
    monthlyPrice: 2900,
    capacity: 12,
    capacityCap: CAPACITY_CAP,
    selfDelivery: true,
    selfDeliveryFee: 25,
    fssaiTier: 'basic-registration',
    fssaiNumber: 'FSSAI-BLR-2024-0098',
    verificationStatus: 'pending',
    zoneId: 'zone-2',
    latitude: 12.9608,
    longitude: 77.5847,
    mealsPerDay: 2,
    activeSubscribers: 8,
  },
  {
    id: 'cook-4',
    userId: 'cook-4',
    name: 'Meena Didi Kitchen',
    tagline: 'Rajasthani ghar ka khana',
    bio: 'I bring the flavours of Rajasthan to Bengaluru. Dal baati, gatte ki sabzi, ker sangri — the kind of food you only get at home, never in a restaurant.',
    kitchenPhoto: kitchenPhotos[3],
    pincodes: ['560002', '560005'],
    rating: 4.6,
    ratingCount: 34,
    weeklyMenu: [
      { day: 'Mon', dish: 'Dal Baati Churma', description: 'Signature Rajasthani dal baati with churma', vegType: 'veg' },
      { day: 'Tue', dish: 'Gatte Ki Sabzi & Roti', description: 'Besan gatte in spiced curd gravy with roti', vegType: 'veg' },
      { day: 'Wed', dish: 'Ker Sangri & Bajra Roti', description: 'Desert beans and berries with millet roti', vegType: 'veg' },
      { day: 'Thu', dish: 'Panchmel Dal & Rice', description: 'Five-lentil dal with steamed rice and ghee', vegType: 'veg' },
      { day: 'Fri', dish: 'Ghevar & Dal', description: 'Sweet ghevar with panchmel dal and roti', vegType: 'veg' },
      { day: 'Sat', dish: 'Laal Maas & Roti', description: 'Fiery red mutton curry with bajra roti', vegType: 'non-veg' },
      { day: 'Sun', dish: 'Rajasthani Thali', description: 'Full thali: 2 sabzi, dal, rice, roti, sweet, papad', vegType: 'veg' },
    ],
    vegType: 'mixed',
    pricePerMeal: 80,
    weeklyPrice: 800,
    monthlyPrice: 3100,
    capacity: 10,
    capacityCap: CAPACITY_CAP,
    selfDelivery: false,
    selfDeliveryFee: 0,
    fssaiTier: 'basic-registration',
    fssaiNumber: 'FSSAI-BLR-2024-0115',
    verificationStatus: 'pending',
    zoneId: 'zone-2',
    latitude: 12.9851,
    longitude: 77.6102,
    mealsPerDay: 2,
    activeSubscribers: 6,
  },
];

export const mockZones: DeliveryZone[] = [
  {
    id: 'zone-4',
    name: 'Greater Noida West — Techzone 4',
    pincode: '201310',
    hasPlatformDelivery: false,
    deliveryFee: 0,
    deliveryWindow: '12:30 PM - 1:30 PM (Lunch) · 7:30 PM - 8:30 PM (Dinner)',
    activeOrders: 0,
  },
  {
    id: 'zone-1',
    name: 'Brigade Road — MG Road',
    pincode: '560001',
    hasPlatformDelivery: true,
    assignedPartnerId: 'partner-ravi-delivery',
    deliveryPartner: 'Ravi Delivery',
    deliveryFee: 30,
    deliveryWindow: '12:30 PM – 1:30 PM (Lunch) · 7:30 PM – 8:30 PM (Dinner)',
    activeOrders: 14,
  },
  {
    id: 'zone-2',
    name: 'Indiranagar — 100ft Road',
    pincode: '560038',
    hasPlatformDelivery: false,
    deliveryFee: 0,
    deliveryWindow: '',
    activeOrders: 0,
  },
  {
    id: 'zone-3',
    name: 'Koramangala — 5th Block',
    pincode: '560095',
    hasPlatformDelivery: true,
    assignedPartnerId: 'partner-quicktiffin',
    deliveryPartner: 'QuickTiffin Logistics',
    deliveryFee: 35,
    deliveryWindow: '12:00 PM – 1:00 PM (Lunch) · 7:00 PM – 8:00 PM (Dinner)',
    activeOrders: 9,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    customerId: 'cust-1',
    cookId: 'cook-1',
    planType: 'weekly',
    mealSlot: 'lunch',
    deliveryMode: 'cook-delivery',
    startDate: '2026-09-07',
    endDate: '2026-09-13',
    daysTotal: 7,
    daysRemaining: 5,
    daysCompleted: 2,
    mealsPerDay: 1,
    pricePerMeal: 70,
    deliveryFee: 20,
    platformFee: PLATFORM_FEE_PER_MEAL,
    totalPaid: 700,
    status: 'active',
    todayCode: '4827',
    todayStatus: 'pending',
    todaySkipped: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    subscriptionId: 'sub-1',
    customerId: 'cust-1',
    cookId: 'cook-1',
    date: '2026-09-07',
    mealSlot: 'lunch',
    status: 'pending',
    handoverCode: '4827',
    deliveryMode: 'cook-delivery',
    customerName: 'Arjun Mehta',
    cookName: 'Lakshmi Aunty',
    pincode: '560001',
    address: '12, Brigade Road, Bengaluru',
  },
  {
    id: 'order-2',
    subscriptionId: 'sub-2',
    customerId: 'cust-2',
    cookId: 'cook-1',
    date: '2026-09-07',
    mealSlot: 'lunch',
    status: 'pending',
    handoverCode: '1395',
    deliveryMode: 'self-pickup',
    customerName: 'Priya Sharma',
    cookName: 'Lakshmi Aunty',
    pincode: '560001',
    address: 'Pickup at cook\'s kitchen',
  },
  {
    id: 'order-3',
    subscriptionId: 'sub-3',
    customerId: 'cust-3',
    cookId: 'cook-1',
    date: '2026-09-07',
    mealSlot: 'lunch',
    status: 'pending',
    handoverCode: '7264',
    deliveryMode: 'platform-delivery',
    customerName: 'Karthik Reddy',
    cookName: 'Lakshmi Aunty',
    pincode: '560001',
    address: '44, Residency Road, Bengaluru',
    zoneId: 'zone-1',
  },
  {
    id: 'order-4',
    subscriptionId: 'sub-4',
    customerId: 'cust-4',
    cookId: 'cook-1',
    date: '2026-09-07',
    mealSlot: 'dinner',
    status: 'confirmed',
    handoverCode: '5519',
    deliveryMode: 'cook-delivery',
    customerName: 'Deepa Nair',
    cookName: 'Lakshmi Aunty',
    pincode: '560001',
    address: '8, Lavelle Road, Bengaluru',
  },
];

export const mockRatings: Rating[] = [
  {
    id: 'rating-1',
    subscriptionId: 'sub-0',
    customerId: 'cust-0',
    cookId: 'cook-1',
    stars: 5,
    comment: 'Tastes exactly like home. The dal is the best part.',
    date: '2026-09-01',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay-1',
    subscriptionId: 'sub-1',
    customerId: 'cust-1',
    cookId: 'cook-1',
    amount: 90,
    platformFee: 15,
    deliveryFee: 20,
    cookEarning: 70,
    deliveryMode: 'cook-delivery',
    date: '2026-09-05',
    status: 'released',
  },
  {
    id: 'pay-2',
    subscriptionId: 'sub-1',
    customerId: 'cust-1',
    cookId: 'cook-1',
    amount: 90,
    platformFee: 15,
    deliveryFee: 20,
    cookEarning: 70,
    deliveryMode: 'cook-delivery',
    date: '2026-09-06',
    status: 'released',
  },
];

export const mockCookPayments: Payment[] = [
  ...mockPayments,
  {
    id: 'pay-3',
    subscriptionId: 'sub-2',
    customerId: 'cust-2',
    cookId: 'cook-1',
    amount: 85,
    platformFee: 15,
    deliveryFee: 0,
    cookEarning: 70,
    deliveryMode: 'self-pickup',
    date: '2026-09-06',
    status: 'released',
  },
  {
    id: 'pay-4',
    subscriptionId: 'sub-3',
    customerId: 'cust-3',
    cookId: 'cook-1',
    amount: 115,
    platformFee: 15,
    deliveryFee: 30,
    cookEarning: 70,
    deliveryMode: 'platform-delivery',
    date: '2026-09-06',
    status: 'released',
  },
  {
    id: 'pay-5',
    subscriptionId: 'sub-4',
    customerId: 'cust-4',
    cookId: 'cook-1',
    amount: 95,
    platformFee: 15,
    deliveryFee: 20,
    cookEarning: 70,
    deliveryMode: 'cook-delivery',
    date: '2026-09-06',
    status: 'released',
  },
];
